<?php

namespace App\Repository;

/**
 * SecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdercRepository extends \Doctrine\ORM\EntityRepository
{
}
